### ISSUE TITLE
Use an existing JSON library

### ISSUE THREAD

**Issue by drjdpowell** [negentropicdev/lv-stream#3]
If you use your own JSON code, then you will have to deal with making it properly compliant with the standard.  UTF-8 conversion, escaping characters, etc.  I suggest my JSONtext, on teh Tools Network, which is widely used and much more flexible than the inbuilt JSON primitive.

**Comment by negentropicdev** [comment]
@drjdpowell I'll add an issue to lv-web-crypto make sure the JSON functionality is UTF-8 compliant.
